# Generated by Django 3.2.15 on 2022-09-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='question_text',
            new_name='text',
        ),
    ]
